server:
  port: 8110

spring:
  application:
    name: service-edu
  datasource:
    url: jdbc:mysql://192.168.100.100:3306/guli_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    druid:
#      url: jdbc:mysql://192.168.100.100:3306/guli_edu?serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 设置日志级别
#logging:
#  level:
#    root: ERROR

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


