server:
  port: 8160
#  tomcat:
#    max-threads: 2

spring:
  application:
    name: service-ucenter
  datasource:
    url: jdbc:mysql://192.168.100.100:3306/guli_ucenter?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
      eager: true
      filter:
        url-patterns:
          - /**
  redis:
    port: 6379
    host: 192.168.100.100
    lettuce:
      pool:
        max-wait: -1  # redis连接不会中断 直到操作成功
        max-idle: 8  # 空闲时最大维护的连接数
        min-idle: 0  # 空闲时最小的连接数
        max-active: 20 # 最大的连接数
feign:
  sentinel:
    enabled: true


# 设置日志级别
#logging:
#  level:
#    root: ERROR

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/*/mapper/xml/*.xml
  type-aliases-package: com.atguigu.guli.service.cms

service-oss: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

wx:
  login:
    qrconnectUrl: https://open.weixin.qq.com/connect/qrconnect
    appid: wxed9954c01bb89b47
    redirectUri: http://localhost:8160/api/ucenter/wx/callback
    accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
    appsecret: a7482517235173ddb4083788de60b90e
    userInfoUrl: https://api.weixin.qq.com/sns/userinfo




