spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**
        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/*/edu/**,/user/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/oss/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**
        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**

  application:
    name: api-gateway
  profiles:
    active: dev

server:
  port: 9110
